### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by haevnEU** [haevnEU/JavaUtils#2]
Implement the possibility for Webhooks. 
- [x] Interface to provide an abstract interaction with webhooks
- [x] Discord webhook implementation
  - [x] Embed
  - [x] Sending

**Comment by nimile** [comment]
- [ ] No unused imports
- [ ] All warnings are evaluated
- [ ] All TODO are evaluated
- [ ] No errors open
- [ ] Build succeed 
- [ ] Code is properly formatted
